In [1]:
import numpy as np


In [9]:
#scenario --->1
#both the matrices has same shape 2*4

a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [7]:
a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [13]:
#scenario ------>2

a3=np.arange(9).reshape(3,3)
a4=np.arange(3).reshape(1,3)
print(a3,a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [15]:
a3+a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

# BROADCASTING
In NumPy, broadcasting refers to a mechanism that allows arrays of different shapes to be used together in arithmetic operations. The basic idea is to extend smaller arrays so that they have compatible shapes for arithmetic operations with larger arrays.

# SOME IMPORTANT FUNCTION---->


In [21]:
np.random.random()

0.4973293426613614

In [31]:
#to get same value every time-------->
np.random.seed(1)
np.random.random()


0.417022004702574

In [37]:
#random value within a given range --->
np.random.uniform(3,10)

5.116328008422879

In [39]:
np.random.uniform(1,100,10)

array([15.52883319, 10.14152088, 19.43976093, 35.21051198, 40.27997995,
       54.34285667, 42.50025693, 68.83673054, 21.24077272, 87.9336262 ])

In [45]:
np.random.uniform(1,100,10).reshape(2,5)

array([[69.49583428, 32.23604747, 68.96359184, 83.62794152,  2.81053946],
       [75.26428718, 98.8972478 , 75.06839978, 28.76395521, 79.13865352]])

In [55]:
#### to generate integer values---->
np.random.randint(1,10,5)

array([3, 8, 8, 8, 4])

In [57]:
np.random.randint(1,10,15).reshape(3,5)

array([[1, 9, 8, 8, 2],
       [2, 4, 1, 9, 7],
       [5, 6, 7, 3, 6]])

In [77]:
a=np.random.randint(1,10,6)
a

array([8, 9, 5, 1, 2, 9])

In [79]:
np.max(a)

9

In [83]:
np.min(a)

1

In [85]:
#index of maximum number---->
np.argmax(a)

1

In [87]:
a[np.argmax(a)]

9

In [89]:
##### index of minimum value----->
np.argmin(a)

3

In [91]:
#to check the min value----->
a[np.argmin(a)]

1

In [93]:
a=np.random.randint(1,10,6)
a

array([3, 4, 2, 3, 8, 3])

In [95]:
a[a%2==1]=-1
a

array([-1,  4,  2, -1,  8, -1])

In [101]:
a=np.random.randint(1,20,6)
a

array([11, 17,  6, 14, 18, 19])

# using where (condition,if condition is TRUE what would be its value, if condition is false what would be its value)

In [104]:
np.where(a%2==1,-1,a)

array([-1, -1,  6, 14, 18, -1])

In [106]:
a

array([11, 17,  6, 14, 18, 19])

In [108]:
#the original array remains the same ^^^^^^^^^

In [112]:
a=np.random.randint(1,20,6)
a

array([15, 14, 12,  7, 14, 16])

In [116]:
# percentile function---->
a=np.random.randint(1,50,10)
a


array([28, 48, 14, 41, 15, 46, 24, 17, 29, 43])

In [120]:
a=np.sort(a)

In [122]:
a

array([14, 15, 17, 24, 28, 29, 41, 43, 46, 48])

In [ ]:
np.percentile(a,50