In [7]:
import numpy as np
#reshape(2,12)----> 2 rows and 12 cols(rows,cols)
arr1=np.arange(24).reshape(2,12)
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [13]:
arr2=np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [19]:
#selecting specific indexes
arr2[2:3]

array([3])

In [21]:
arr2[-1]

5

In [27]:
#for having a single row
arr1[1]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [31]:
arr1=np.arange(24).reshape(6,4)

In [33]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
arr1[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [37]:
#for printing all the columns -------.>
arr1[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [41]:
#for second and third col----->
arr1[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [47]:
#to have elements 9,10,13,14---->

arr1[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [49]:
#to print 18,19,22,23------->
arr1[4:6,2:4]

array([[18, 19],
       [22, 23]])

In [51]:
arr4=np.arange(24)

array([1, 2, 3, 4, 5])

In [57]:
for i in arr2:
   print(i)

1
2
3
4
5


In [61]:
for i in np.nditer(arr2):
   print(i)

1
2
3
4
5
