In [1]:
print("hello himanshi")


hello himanshi


In [3]:
import numpy as np

In [5]:
arr1=np.array([1,2,3,4,5])

In [7]:
arr1

array([1, 2, 3, 4, 5])

In [11]:
#to find the type
type(arr1)


numpy.ndarray

In [13]:
arr2=np.array([[1,2,3],[4,5,6]])

In [15]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr3=np.zeros((2,3))

In [19]:
arr3


array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr5=np.identity(5)


In [23]:
arr5


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr7=np.arange(5,16)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
#linspace basically makes equidistance elements

arr8=np.linspace(10,20,10)
arr8


array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [33]:
arr9=arr8.copy()

In [35]:
arr9


array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])