In [1]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [7]:
#element wise substraction
arr1-arr2


array([-3, -3, -3, -3, -3, -3])

In [17]:
#every item got multiplied--->vector multiplication
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [15]:
arr1*2
# this is scaler multiplication

array([ 2,  4,  6,  8, 10, 12])

In [21]:
arr2>3
#gives true everywhere the condition is trueee------>

array([ True,  True,  True,  True,  True,  True])

In [25]:
#matrix multiplication --->

arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [27]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [29]:
arr4.max()

11

In [31]:
arr4.min()

6

In [45]:
arr4.min(axis=0)
#that means to tell about cols

array([6, 7])

In [47]:
arr4.min(axis=1)
#gives max of each and every row

array([ 6,  8, 10])

In [49]:
arr4.sum()

51

In [51]:
arr4.sum(axis=0)

array([24, 27])

In [53]:
arr4.mean()

8.5

In [55]:
arr4.sum()

51

In [61]:
# that tells about the standard deviation---->

arr4.std()

1.707825127659933

In [63]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [65]:
np.median(arr4)

8.5

In [67]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [69]:
####### reshaping numpy arrays

arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [73]:
arr4.ndim

#tells the dimension

2

In [77]:
arr4.ravel()
#ravel function coverte 2d,3d and big dimentions arrays into 1d array

array([ 6,  7,  8,  9, 10, 11])

In [79]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [81]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [83]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [95]:
arr5=np.arange(12,18).reshape(2,3)

In [97]:
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [101]:
np.hstack((arr3,arr5))
#joins two arrays horizontally

array([[12, 13, 14, 12, 13, 14],
       [15, 16, 17, 15, 16, 17]])

In [103]:
arr3

array([[12, 13, 14],
       [15, 16, 17]])

In [105]:
#how many equal horizonal parts in which it can be splitted into---->

np.hsplit(arr3,3)

[array([[12],
        [15]]),
 array([[13],
        [16]]),
 array([[14],
        [17]])]

In [113]:
#for vertical split---->
np.vsplit(arr3,2)

[array([[12, 13, 14]]), array([[15, 16, 17]])]

In [116]:
######################################FANCY INDEXING------------------------>
arr8=np.arange(24).reshape(6,4)

In [118]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [122]:
arr8[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])