In [19]:
import numpy as np
arr1=np.array([1,2,3,4,5])

In [20]:
arr1


array([1, 2, 3, 4, 5])

In [21]:
#properties----------->
arr1.shape


(5,)

In [22]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr2.shape

(2, 3)

In [24]:
arr9=np.array([[1,2],[3,4],[5,6],[7,8]])

In [25]:
arr9

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
arr9.shape

(4, 2)

In [27]:
arr9.ndim

2

In [28]:
#number of items---------->
arr1.size


5

In [29]:
arr9.size

8

In [30]:
#itemsize------------->
arr9.itemsize

8

In [31]:
#to find data type----->
arr1.dtype


dtype('int64')

In [32]:
#coverting data type---->
arr1.astype('float')

array([1., 2., 3., 4., 5.])

In [33]:
#lists Vs Numpy--------->
lista=range(100)
arr11=np.arange(100)

In [34]:
import sys
print(sys.getsizeof(87)*len(lista))

2800


In [35]:
print(arr11.itemsize*arr11.size)

800


In [36]:
#hence numpy array saves memory and uses less memory
import time
x=range(10000000)
y=range(10000000,200000)

In [37]:
start_time=time.time()
c=[(x,y) for x,y in zip(x,y)]

print(time.time()-start_time)

4.518054008483887


In [41]:
a=np.arange(10000000)
b=np.arange(10000000,200000)
start_time=time.time()
c=a+b
print(time.time()-start_time)

ValueError: operands could not be broadcast together with shapes (10000000,) (0,) 